[general]
import = [
	"~/.config/alacritty/themes/rose-pine-moon.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
dynamic_title = false
option_as_alt = "OnlyLeft"

[font]
normal.family = "CaskaydiaMono Nerd Font"
size = 16
