vim.cmd 'highlight clear'
if vim.fn.exists 'syntax_on' == 1 then vim.cmd 'syntax reset' end
vim.g.colors_name = 'alabaster-dusk'
vim.o.background = 'dark'

local c = {
  bg        = '#120f18',
  bg_subtle = '#201828',
  bg_float  = '#181520',
  border    = '#382840',
  line_nr   = '#382840',
  muted     = '#7a5888',
  comment   = '#50b0a8',
  fg        = '#c8c0d2',
  accent    = '#b078b8',
  error     = '#c04858',
  warn      = '#a87840',
  ok        = '#6aaa60',
  info      = '#6080b8',
  search    = '#2a1535',
  bracket   = '#6080b8',
  none      = 'NONE',
}

local hi = function(name, opts) vim.api.nvim_set_hl(0, name, opts) end

hi('Normal',           { fg = c.fg,     bg = c.bg })
hi('NormalFloat',      { fg = c.fg,     bg = c.bg_float })
hi('NormalNC',         { fg = c.fg,     bg = c.bg })
hi('FloatBorder',      { fg = c.border, bg = c.bg_float })
hi('FloatTitle',       { fg = c.accent, bg = c.bg_float, bold = true })

hi('Cursor',           { fg = c.bg,     bg = c.fg })
hi('CursorIM',         { fg = c.bg,     bg = c.fg })
hi('CursorLine',       { bg = c.bg_subtle })
hi('CursorColumn',     { bg = c.bg_subtle })
hi('CursorLineNr',     { fg = c.accent, bg = c.bg_subtle })
hi('TermCursor',       { fg = c.bg,     bg = c.accent })

hi('Visual',           { bg = c.bg_subtle })
hi('VisualNOS',        { bg = c.bg_subtle })
hi('Search',           { fg = c.fg,     bg = c.search })
hi('IncSearch',        { fg = c.bg,     bg = c.accent, bold = true })
hi('Substitute',       { fg = c.bg,     bg = c.accent })
hi('QuickFixLine',     { bg = c.bg_subtle })

hi('StatusLine',       { fg = c.fg,     bg = c.bg_subtle })
hi('StatusLineNC',     { fg = c.muted,  bg = c.bg })
hi('TabLine',          { fg = c.muted,  bg = c.bg })
hi('TabLineFill',      { bg = c.bg })
hi('TabLineSel',       { fg = c.accent, bg = c.bg_subtle, bold = true })
hi('WinBar',           { fg = c.fg,     bg = c.bg_subtle })
hi('WinBarNC',         { fg = c.muted,  bg = c.bg })
hi('WinSeparator',     { fg = c.border })
hi('VertSplit',        { fg = c.border })

hi('LineNr',           { fg = c.line_nr })
hi('SignColumn',       { fg = c.line_nr, bg = c.bg })
hi('FoldColumn',       { fg = c.line_nr, bg = c.bg })
hi('Folded',           { fg = c.muted,  bg = c.bg_subtle })
hi('ColorColumn',      { bg = c.bg_subtle })

hi('Pmenu',            { fg = c.fg,     bg = c.bg_float })
hi('PmenuSel',         { fg = c.fg,     bg = c.bg_subtle })
hi('PmenuSbar',        { bg = c.bg_subtle })
hi('PmenuThumb',       { bg = c.border })
hi('WildMenu',         { fg = c.bg,     bg = c.accent })

hi('ErrorMsg',         { fg = c.error })
hi('WarningMsg',       { fg = c.warn })
hi('MoreMsg',          { fg = c.accent })
hi('Question',         { fg = c.accent })
hi('ModeMsg',          { fg = c.fg, bold = true })
hi('MsgArea',          { fg = c.fg,     bg = c.bg })

hi('MatchParen',       { fg = c.accent, bold = true, underline = true })
hi('Title',            { fg = c.accent, bold = true })
hi('Directory',        { fg = c.accent })
hi('NonText',          { fg = c.border })
hi('SpecialKey',       { fg = c.border })
hi('Whitespace',       { fg = c.border })
hi('EndOfBuffer',      { fg = c.border })
hi('Conceal',          { fg = c.muted })

hi('Comment',          { fg = c.comment, italic = true })
hi('String',           { fg = c.accent })
hi('Character',        { fg = c.accent })
hi('Number',           { fg = c.accent })
hi('Float',            { fg = c.accent })
hi('Boolean',          { fg = c.accent })
hi('Constant',         { fg = c.accent })
hi('SpecialChar',      { fg = c.accent })
hi('Special',          { fg = c.accent })
hi('Todo',             { fg = c.accent, bold = true })
hi('Debug',            { fg = c.accent })

hi('Identifier',       { fg = c.fg })
hi('Function',         { fg = c.fg })
hi('Statement',        { fg = c.fg })
hi('Keyword',          { fg = c.fg })
hi('Conditional',      { fg = c.fg })
hi('Repeat',           { fg = c.fg })
hi('Label',            { fg = c.fg })
hi('Operator',         { fg = c.fg })
hi('Exception',        { fg = c.fg })
hi('Type',             { fg = c.fg })
hi('StorageClass',     { fg = c.fg })
hi('Structure',        { fg = c.fg })
hi('Typedef',          { fg = c.fg })
hi('PreProc',          { fg = c.fg })
hi('Include',          { fg = c.fg })
hi('Define',           { fg = c.fg })
hi('Macro',            { fg = c.fg })
hi('PreCondit',        { fg = c.fg })
hi('Delimiter',        { fg = c.fg })
hi('Tag',              { fg = c.fg })
hi('Underlined',       { fg = c.fg, underline = true })
hi('Bold',             { bold = true })
hi('Italic',           { italic = true })
hi('Error',            { fg = c.error })

hi('DiffAdd',          { bg = '#142314' })
hi('DiffChange',       { bg = '#1e1428' })
hi('DiffDelete',       { fg = c.border, bg = '#280e14' })
hi('DiffText',         { fg = c.accent, bg = '#2a1535' })
hi('Added',            { fg = c.ok })
hi('Changed',          { fg = c.accent })
hi('Removed',          { fg = c.error })

hi('SpellBad',         { undercurl = true, sp = c.error })
hi('SpellCap',         { undercurl = true, sp = c.warn })
hi('SpellLocal',       { undercurl = true, sp = c.info })
hi('SpellRare',        { undercurl = true, sp = c.muted })

hi('@comment',                  { link = 'Comment' })
hi('@comment.documentation',    { link = 'Comment' })
hi('@string',                   { link = 'String' })
hi('@string.escape',            { fg = c.accent, bold = true })
hi('@string.special',           { link = 'String' })
hi('@string.special.url',       { fg = c.accent, underline = true })
hi('@string.documentation',     { link = 'Comment' })
hi('@character',                { link = 'String' })
hi('@number',                   { link = 'Number' })
hi('@number.float',             { link = 'Float' })
hi('@boolean',                  { link = 'Boolean' })
hi('@constant',                 { link = 'Constant' })
hi('@constant.builtin',         { link = 'Constant' })
hi('@constant.macro',           { link = 'Constant' })
hi('@keyword',                  { link = 'Normal' })
hi('@keyword.function',         { link = 'Normal' })
hi('@keyword.operator',         { fg = c.accent })
hi('@keyword.return',           { link = 'Normal' })
hi('@keyword.import',           { link = 'Normal' })
hi('@keyword.coroutine',        { link = 'Normal' })
hi('@keyword.conditional',      { link = 'Normal' })
hi('@keyword.repeat',           { link = 'Normal' })
hi('@keyword.exception',        { link = 'Normal' })
hi('@keyword.debug',            { link = 'Normal' })
hi('@operator',                 { link = 'Normal' })
hi('@punctuation',              { link = 'Normal' })
hi('@punctuation.bracket',      { fg = c.bracket })
hi('@punctuation.delimiter',    { link = 'Normal' })
hi('@punctuation.special',      { link = 'Normal' })
hi('@variable',                 { link = 'Normal' })
hi('@variable.builtin',         { link = 'Normal' })
hi('@variable.parameter',       { link = 'Normal' })
hi('@variable.member',          { link = 'Normal' })
hi('@function',                 { link = 'Normal' })
hi('@function.call',            { link = 'Normal' })
hi('@function.builtin',         { link = 'Normal' })
hi('@function.macro',           { link = 'Normal' })
hi('@function.method',          { link = 'Normal' })
hi('@function.method.call',     { link = 'Normal' })
hi('@constructor',              { link = 'Normal' })
hi('@type',                     { link = 'Normal' })
hi('@type.builtin',             { link = 'Normal' })
hi('@type.qualifier',           { link = 'Normal' })
hi('@type.definition',          { link = 'Normal' })
hi('@namespace',                { link = 'Normal' })
hi('@module',                   { link = 'Normal' })
hi('@label',                    { link = 'Normal' })
hi('@tag',                      { link = 'Normal' })
hi('@tag.attribute',            { link = 'String' })
hi('@tag.delimiter',            { link = 'Normal' })
hi('@attribute',                { link = 'Normal' })
hi('@property',                 { link = 'Normal' })
hi('@field',                    { link = 'Normal' })
hi('@define',                   { link = 'Normal' })
hi('@preproc',                  { link = 'Normal' })
hi('@annotation',               { link = 'Normal' })
hi('@error',                    { link = 'Error' })
hi('@spell',                    { link = 'SpellBad' })

hi('@lsp.type.keyword',         { link = 'Normal' })
hi('@lsp.type.operator',        { link = 'Normal' })
hi('@lsp.type.variable',        { link = 'Normal' })
hi('@lsp.type.parameter',       { link = 'Normal' })
hi('@lsp.type.property',        { link = 'Normal' })
hi('@lsp.type.function',        { link = 'Normal' })
hi('@lsp.type.method',          { link = 'Normal' })
hi('@lsp.type.type',            { link = 'Normal' })
hi('@lsp.type.class',           { link = 'Normal' })
hi('@lsp.type.interface',       { link = 'Normal' })
hi('@lsp.type.struct',          { link = 'Normal' })
hi('@lsp.type.enum',            { link = 'Normal' })
hi('@lsp.type.enumMember',      { link = 'Constant' })
hi('@lsp.type.string',          { link = 'String' })
hi('@lsp.type.number',          { link = 'Number' })
hi('@lsp.type.boolean',         { link = 'Boolean' })
hi('@lsp.type.namespace',       { link = 'Normal' })
hi('@lsp.type.decorator',       { link = 'Normal' })
hi('@lsp.type.comment',         { link = 'Comment' })
hi('@lsp.mod.readonly',         { link = 'Normal' })
hi('@lsp.mod.defaultLibrary',   { link = 'Normal' })

hi('DiagnosticError',                { fg = c.error })
hi('DiagnosticWarn',                 { fg = c.warn })
hi('DiagnosticInfo',                 { fg = c.info })
hi('DiagnosticHint',                 { fg = c.muted })
hi('DiagnosticOk',                   { fg = c.ok })
hi('DiagnosticVirtualTextError',     { fg = c.error, bg = '#200d12' })
hi('DiagnosticVirtualTextWarn',      { fg = c.warn,  bg = '#1e1408' })
hi('DiagnosticVirtualTextInfo',      { fg = c.info,  bg = '#101428' })
hi('DiagnosticVirtualTextHint',      { fg = c.muted, bg = c.bg_subtle })
hi('DiagnosticUnderlineError',       { undercurl = true, sp = c.error })
hi('DiagnosticUnderlineWarn',        { undercurl = true, sp = c.warn })
hi('DiagnosticUnderlineInfo',        { undercurl = true, sp = c.info })
hi('DiagnosticUnderlineHint',        { undercurl = true, sp = c.muted })
hi('DiagnosticFloatingError',        { fg = c.error, bg = c.bg_float })
hi('DiagnosticFloatingWarn',         { fg = c.warn,  bg = c.bg_float })
hi('DiagnosticFloatingInfo',         { fg = c.info,  bg = c.bg_float })
hi('DiagnosticFloatingHint',         { fg = c.muted, bg = c.bg_float })
hi('DiagnosticSignError',            { fg = c.error, bg = c.bg })
hi('DiagnosticSignWarn',             { fg = c.warn,  bg = c.bg })
hi('DiagnosticSignInfo',             { fg = c.info,  bg = c.bg })
hi('DiagnosticSignHint',             { fg = c.muted, bg = c.bg })

hi('GitSignsAdd',                    { fg = c.ok,    bg = c.bg })
hi('GitSignsChange',                 { fg = c.accent, bg = c.bg })
hi('GitSignsDelete',                 { fg = c.error,  bg = c.bg })
hi('GitSignsAddNr',                  { link = 'GitSignsAdd' })
hi('GitSignsChangeNr',               { link = 'GitSignsChange' })
hi('GitSignsDeleteNr',               { link = 'GitSignsDelete' })
hi('GitSignsAddLn',                  { bg = '#142314' })
hi('GitSignsChangeLn',               { bg = '#1e1428' })
hi('GitSignsDeleteLn',               { bg = '#280e14' })

hi('TelescopeNormal',                { fg = c.fg,    bg = c.bg_float })
hi('TelescopeBorder',                { fg = c.border, bg = c.bg_float })
hi('TelescopePromptNormal',          { fg = c.fg,    bg = c.bg_subtle })
hi('TelescopePromptBorder',          { fg = c.border, bg = c.bg_subtle })
hi('TelescopePromptTitle',           { fg = c.accent, bg = c.bg_subtle, bold = true })
hi('TelescopeResultsTitle',          { fg = c.muted,  bg = c.bg_float })
hi('TelescopePreviewTitle',          { fg = c.muted,  bg = c.bg_float })
hi('TelescopeSelection',             { bg = c.bg_subtle })
hi('TelescopeSelectionCaret',        { fg = c.accent, bg = c.bg_subtle })
hi('TelescopeMatching',              { fg = c.accent, bold = true })
hi('TelescopeMultiSelection',        { fg = c.muted })

hi('TroubleNormal',                  { fg = c.fg,    bg = c.bg })
hi('TroubleText',                    { fg = c.fg })
hi('TroubleCount',                   { fg = c.accent, bold = true })
hi('TroubleSource',                  { fg = c.muted })
hi('TroubleLocation',                { fg = c.muted })
hi('TroubleIndent',                  { fg = c.border })
hi('TroubleFoldIcon',                { fg = c.accent })
hi('TroubleSignError',               { link = 'DiagnosticSignError' })
hi('TroubleSignWarning',             { link = 'DiagnosticSignWarn' })
hi('TroubleSignInformation',         { link = 'DiagnosticSignInfo' })
hi('TroubleSignHint',                { link = 'DiagnosticSignHint' })

hi('IblIndent',                      { fg = c.bg_subtle })
hi('IblScope',                       { fg = c.border })
