# Ensure the terminal uses the proper color mode
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Rebind prefix
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# Rebind config refresh
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Splits inherit the current pane's path
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind _ split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"

# Bind pane resizing and maximizing
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z

# Mouse + vi copy mode
set -g mouse on
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Index windows from one and prevent gaps when closing them
set -g base-index 1
set -g renumber-windows on

# Temporary UI popups
bind t display-popup                                                      # Shell
bind g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E "lazygit" # Lazygit
bind b run-shell "tmux capture-pane -S -100 && tmux save-buffer /tmp/tmux-cap" \; display-popup -w 90% -h 90% -E "nvim + /tmp/tmux-cap" # Buffer content

# Custom, non-TPM themes
# source-file ~/.config/tmux/themes/alabaster-dusk.conf

# Plugins (managed as git submodules, sourced directly)
run-shell ~/.config/tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.config/tmux/plugins/tmux-continuum/continuum.tmux
run-shell ~/.config/tmux/plugins/vim-tmux-navigator/vim-tmux-navigator.tmux

# Plugin configuration
set -g @continuum-restore 'on'
